on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: yarn install --immutable
      - name: Run build
        run: yarn build
      - name: Run tests
        run: yarn test
#      - name: Reset git
#        run: git reset --hard
      - name: Publish
        run: lerna publish from-package --yes --no-push --no-git-reset --no-verify-access
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
